<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="/img/icone deployme.png">
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <!-- Bootstrap Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/emoji-picker-element@^1/index.js" type="module"></script>
    <link rel="stylesheet" href="/css/index.css">
    <link rel="stylesheet" href="/css/signup.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/login.css">
    <link rel="stylesheet" href="/css/timeline.css">
    <link rel="stylesheet" href="/css/profile.css">
    <link rel="stylesheet" href="/css/vacancyCandidates.css">
    <link rel="stylesheet" href="/css/chat.css">
    <link rel="stylesheet" href="/css/notification.css">
    <title>Deployme</title>
</head>

<body>
    <?= $this->content(); ?>
    <script src="/js/index.js"> </script>
    <script src="/js/app.js"> </script>
    <script src="/js/AIAnalyzer.js"> </script>
    <script src="/js/repo.js"> </script>
    <script src="/js/ajaxLike.js"> </script>
    <script src="/js/ajaxComment.js"> </script>
    <script src="/js/people.js"> </script>
    <script src="/js/chat.js"></script>
    <script src="/js/viewVacancies.js"></script>
    <script src="/js/notifications.js"></script>
    <script src="/js/profile.js"></script>
</body>

</html>