<nav class="navbar-custom">

    <!-- ESQUERDA -->
    <div class="nav-left">

        <a href="/timeline">

            <img src="/img/logo_deployme.png" alt="Deployme" class="logo-navbar">

        </a>

    </div>

    <!-- CENTRO -->
    <div class="nav-center">

        <a href="/people" class="nav-icon text-decoration-none">

            <i class="bi bi-people"></i>

            <span>Pessoas</span>

        </a>

        <?php if ($tipo == 'estudante') { ?>

            <div class="nav-icon">

                <i class="bi bi-briefcase"></i>

                <span>Minhas candidaturas</span>

            </div>

            <div class="nav-icon">

                <i class="bi bi-globe"></i>

                <span>Ver vagas</span>

            </div>

        <?php } ?>

        <?php if ($tipo == 'recrutador') { ?>

            <div class="nav-icon">

                <i class="bi bi-file-earmark-text"></i>

                <span>Vagas postadas</span>

            </div>

            <div class="nav-icon">

                <i class="bi bi-people-fill"></i>

                <span>Candidaturas</span>

            </div>

        <?php } ?>

        <div class="nav-icon">

            <i class="bi bi-chat-dots"></i>

            <span>Chat</span>

        </div>

        <div class="nav-icon position-relative">

            <i class="bi bi-bell"></i>

            <span>Notificações</span>

            <span class="notification-badge">

                3

            </span>

        </div>

    </div>

    <!-- DIREITA -->
    <div class="nav-right">

        <a href="/logout" class="nav-icon logout text-decoration-none">

            <i class="bi bi-box-arrow-right"></i>

            <span>Sair</span>

        </a>

    </div>

</nav>